apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: question-gen
spec:
  description: >-
    These task evaluate embedding file on for different llms  

  workspaces:
    - name: persist-source
      description: shared Workspace containing the data to embed
    - name: output
      description: evaluation
    - name: source
      description: shared Workspace containing the data to embed
  params:
    - name: provider
      type: string
      description: name of provider [bam,openai]
      default: bam

    - name: model
      type: string
      description: model 
      default: local:BAAI/bge-base-en

    - name: product-index
      type: string
      description: storage product index
      default: product

    - name: input-persist-dir
      type: string
      description: path to persist file folder 
      default: "."

    - name: question-main-folder
      type: string
      description: plain text main folder path used for question generation 


    - name: number-of-questions
      type: string
      description: vector db port  
      default: "5"

    - name: similarity
      type: string
      default: "1"

    - name: chunk-size
      type: string
      default: "1024"
      description: chunk size for embedding

    - name: chunk-overlap
      type: string
      default: "20"
      description: chunk overlap for embedding

  results:
    - name: status
      description: task status 
  steps:
    - name: question-gen
      image: "quay.io/redhat_emp1/rag-pipeline-tasks:latest"
      imagePullPolicy: Always
      envFrom:
          - secretRef:
              name: secret-openai
          - secretRef:
              name: secret-bam

      env:
      - name: PROVIDER
        value: "$(params.provider)"
      - name: MODEL
        value: "$(params.model)"
      - name: PRODUCT_INDEX
        value: $(params.product-index)
      - name: INPUT_PERSIST_DIR
        value: $(params.input-persist-dir)
      - name: QUESTION_FOLDER
        value: $(params.question-main-folder)

      - name: SIMILARITY
        value: $(params.similarity)

      - name:  NUMBER_OF_QUESTIONS
        value: $(params.number-of-questions)

      - name: OUTPUT_PATH
        value: $(workspaces.output.path)/data

      - name: CHUNK_SIZE
        value: $(params.chunk-size)

      - name: CHUNK_OVERLAP
        value: $(params.chunk-overlap)

      - name: TOKENIZERS_PARALLELISM
        value: "false"
      script: |
        #!/usr/bin/env sh
        set -eu

        echo "-p ${PROVIDER} \
              -i ${INPUT_PERSIST_DIR} \ 
              -x ${PRODUCT_INDEX} \
              -m ${MODEL} \
              -o ${OUTPUT_PATH} \
              -q ${QUESTION_FOLDER}\
              -s ${SIMILARITY} \
              -n ${NUMBER_OF_QUESTIONS}
              "

        python questions_gen.py -p ${PROVIDER} -i ${INPUT_PERSIST_DIR} -x ${PRODUCT_INDEX} -m ${MODEL} -o ${OUTPUT_PATH} -q ${QUESTION_FOLDER} -s ${SIMILARITY} -n ${NUMBER_OF_QUESTIONS} -c ${CHUNK_SIZE} -l ${CHUNK_OVERLAP}

        mv ${OUTPUT_PATH}/*.md $(workspaces.output.path)

